apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
#  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.6.8
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.3/manifests/install.yaml 
  - resources/namespace.yaml

patches:
- path: argocd-dex-server.yaml
#- path: patches/argocd-cm.yaml
#- path: patches/argocd-cmd-params-cm.yaml
#- path: patches/argocd-server-deployment.yaml
#- path: patches/argocd-repo-server-deployment.yaml
#- path: patches/argocd-application-controller-statefulset.yaml
#- path: patches/argocd-istio.yaml
